### ISSUE TITLE
on PlatformException catch (e) not being called on result.error

### ISSUE THREAD

**Issue by cahyowhy** [pycampers/flutter-plugin-scaffold#5]
i sent result.error from native but on my dart code the exception not being invoked..
instead its only show
```D/PluginScaffold( 9179): Ignoring exception: <java.lang.IllegalStateException: Reply already submitted>. See https://github.com/flutter/flutter/issues/29092 for details.```

this is my native method
```
public void doStartOvoHandler() {
        mCLOvoHandler.doStartOvoHandler();
        this.result.success(true);
}
```

and this is my dart code
```
static Future<bool> doStartOvoPayment() async {
    try {
      const platform = MethodChannel(Constant.METHOD_CHANEL);

      var ovoStartResponse = await platform.invokeMethod('cashlezOvoStart');

      return ovoStartResponse;
    } on PlatformException catch (e) {
      print(e);
    }

    return null;
  }
```

**Comment by devxpy** [comment]
I don't see a `result.error` call in the code you provided. 

Please provide a minimum reproducible example so I can see what's wrong here.

**Comment by devxpy** [comment]
On second thought, if you want plugin scaffold to catch an `IllegalStateException` (except the one from https://github.com/flutter/flutter/issues/29092) and pipe it to dart, we can try to make that happen.

**Comment by cahyowhy** [comment]
the result.error was invoked on another method. it seems in my case was the result error/success was not invoked after```<java.lang.IllegalStateException: Reply already submitted>```
and now i refactor my code to see where the result success/error was invoked twice and it works.
