### ISSUE TITLE
Prevent logs

### ISSUE THREAD

**Issue by OrgesKreka** [pycampers/flutter-plugin-scaffold#6]
Hi, is there any way to prevent the library logging sensitive data.
 I am using the flutter_cognito_plugin library and any time i call the sign in method it logs the credentials:
`
D/PluginScaffold( 4809): invoke { channel: com.pycampers.flutter_cognito_plugin, method: signIn(), args: {password=****, username=foo@foo.gmail.com} }
`
How can i disable this behaviour?

**Comment by devxpy** [comment]
Use proguard.

**Comment by OrgesKreka** [comment]
@devxpy  thank you for the fast replay.
But beside proguard is'n there any other way to disable logging ?

**Comment by mario-neb** [comment]
Hey, 
I tried using proguard but these logs are still showing up.
